# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  name: Azure Pipelines
  vmImage: ubuntu-latest
jobs:
  - job: Build
    displayName: Build
    workspace:
      clean: outputs
    steps:
    # - task: NodeTool@0
    #   inputs:
    #     versionSpec: '18.x'
    #   displayName: 'Install Node.js'
    - script: |
        ls -l
        pwd
        whoami
 